//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Configuration;

namespace SchoolManagementSystem
{
    
    public partial class BioData
      
    {
        protected global::System.Web.UI.WebControls.TextBox UserId;
        protected global::System.Web.UI.WebControls.TextBox UserName;
        protected global::System.Web.UI.WebControls.TextBox FName;
        protected global::System.Web.UI.WebControls.TextBox lName;
        protected global::System.Web.UI.WebControls.TextBox gender;
        protected global::System.Web.UI.WebControls.TextBox role;
        protected global::System.Web.UI.WebControls.TextBox email;
        protected global::System.Web.UI.WebControls.TextBox telphone1;
        protected global::System.Web.UI.WebControls.TextBox telphone2;

    }
}
